/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngredientResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pantry-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    category?: string;
                    expiringSoon?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PantryItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["AddPantryItemRequest"];
                    "text/json": null | components["schemas"]["AddPantryItemRequest"];
                    "application/*+json": null | components["schemas"]["AddPantryItemRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PantryItemResponse"];
                        "application/json": components["schemas"]["PantryItemResponse"];
                        "text/json": components["schemas"]["PantryItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pantry-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["UpdatePantryItemRequest"];
                    "text/json": null | components["schemas"]["UpdatePantryItemRequest"];
                    "application/*+json": null | components["schemas"]["UpdatePantryItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PantryItemResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["RegisterRequest"];
                    "text/json": null | components["schemas"]["RegisterRequest"];
                    "application/*+json": null | components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["LoginRequest"];
                    "text/json": null | components["schemas"]["LoginRequest"];
                    "application/*+json": null | components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/antiforgery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AntiforgeryTokenResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddPantryItemRequest: {
            /** Format: uuid */
            ingredientId: null | string;
            /** Format: double */
            amount: null | number;
            unit: null | string;
            category?: null | string;
            /** Format: date */
            expiryDate?: null | string;
        };
        AntiforgeryTokenResponse: {
            requestToken: string;
        };
        /** @enum {unknown} */
        Category: "dairy" | "cheese" | "eggs" | "freshMeatFish" | "processedMeat" | "vegetables" | "fruit" | "bakery" | "dryGoods" | "cannedAndSauces" | "frozen" | "beverages" | "preparedFood" | "other";
        CategoryResponse: {
            category: components["schemas"]["Category"];
            /** Format: int32 */
            shelfLifeDays: null | number;
        };
        /** @enum {unknown} */
        Dimension: "mass" | "volume" | "count";
        IngredientResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            dimension: components["schemas"]["Dimension"];
            defaultCategory: components["schemas"]["Category"];
        };
        LoginRequest: {
            email: null | string;
            password: null | string;
        };
        MeResponse: {
            email: string;
            /** Format: uuid */
            householdId: string;
        };
        PantryItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ingredientId: string;
            ingredientName: string;
            /** Format: double */
            amount: number;
            unit: components["schemas"]["Unit"];
            /** Format: double */
            quantity: number;
            category: components["schemas"]["Category"];
            /** Format: date */
            expiryDate: string;
            expiryEstimated: boolean;
            expired: boolean;
            soonExpiring: boolean;
            /** Format: uint32 */
            version: number;
        };
        RegisterRequest: {
            email: null | string;
            password: null | string;
        };
        /** @enum {unknown} */
        Unit: "g" | "dkg" | "kg" | "ml" | "dl" | "l" | "db";
        UpdatePantryItemRequest: {
            /** Format: double */
            amount: null | number;
            unit: null | string;
            category: null | string;
            /** Format: date */
            expiryDate?: null | string;
            reason?: null | string;
            /** Format: uint32 */
            version: null | number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
