// <auto-generated />
using System;
using KamraApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KamraApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KamraDbContext))]
    [Migration("20261010164249_AddIngredientsAndPantryItems")]
    partial class AddIngredientsAndPantryItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KamraApp.Domain.Households.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("Households");
                });

            modelBuilder.Entity("KamraApp.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeedKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("\"HouseholdId\" IS NULL");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasFilter("\"SeedKey\" IS NOT NULL");

                    b.HasIndex("HouseholdId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("\"HouseholdId\" IS NOT NULL");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a126a0-f496-7926-80c2-fffa4640a3c7"),
                            DefaultCategory = "Vegetables",
                            Dimension = "Mass",
                            Name = "paprika",
                            NormalizedName = "paprika",
                            SeedKey = "paprika"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f497-711a-a974-dff897cec5ad"),
                            DefaultCategory = "Vegetables",
                            Dimension = "Mass",
                            Name = "paradicsom",
                            NormalizedName = "paradicsom",
                            SeedKey = "paradicsom"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f498-7ceb-818b-3d4613bec488"),
                            DefaultCategory = "Vegetables",
                            Dimension = "Mass",
                            Name = "vöröshagyma",
                            NormalizedName = "vöröshagyma",
                            SeedKey = "voroshagyma"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f499-70f0-baca-644f79523c11"),
                            DefaultCategory = "Vegetables",
                            Dimension = "Mass",
                            Name = "burgonya",
                            NormalizedName = "burgonya",
                            SeedKey = "burgonya"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f49a-71be-8b17-cb68391f337b"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Volume",
                            Name = "étolaj",
                            NormalizedName = "étolaj",
                            SeedKey = "etolaj"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f49b-7dc6-bf52-af8623e29f9b"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Mass",
                            Name = "száraztészta",
                            NormalizedName = "száraztészta",
                            SeedKey = "szarazteszta"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f49c-7f22-8df0-24c8b87a3b6d"),
                            DefaultCategory = "Dairy",
                            Dimension = "Mass",
                            Name = "túró",
                            NormalizedName = "túró",
                            SeedKey = "turo"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f49d-7056-b903-76a6f2b64b57"),
                            DefaultCategory = "Dairy",
                            Dimension = "Mass",
                            Name = "tejföl",
                            NormalizedName = "tejföl",
                            SeedKey = "tejfol"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f49e-7d6a-b637-443ba18a4984"),
                            DefaultCategory = "ProcessedMeat",
                            Dimension = "Mass",
                            Name = "szalonna",
                            NormalizedName = "szalonna",
                            SeedKey = "szalonna"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f49f-7974-9214-d4c1336a00ff"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Mass",
                            Name = "finomliszt",
                            NormalizedName = "finomliszt",
                            SeedKey = "finomliszt"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a0-7528-a0fa-827975890a2c"),
                            DefaultCategory = "Dairy",
                            Dimension = "Volume",
                            Name = "tej",
                            NormalizedName = "tej",
                            SeedKey = "tej"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a1-76ae-8300-46253511172a"),
                            DefaultCategory = "Eggs",
                            Dimension = "Count",
                            Name = "tojás",
                            NormalizedName = "tojás",
                            SeedKey = "tojas"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a2-7ba6-9efe-59bd7fd8e1bc"),
                            DefaultCategory = "Dairy",
                            Dimension = "Mass",
                            Name = "vaj",
                            NormalizedName = "vaj",
                            SeedKey = "vaj"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a3-761c-ba7a-3ba388ba03e9"),
                            DefaultCategory = "ProcessedMeat",
                            Dimension = "Mass",
                            Name = "kolbász",
                            NormalizedName = "kolbász",
                            SeedKey = "kolbasz"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a4-748b-acd6-1ce2382afd1e"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Mass",
                            Name = "őrölt pirospaprika",
                            NormalizedName = "őrölt pirospaprika",
                            SeedKey = "orolt-pirospaprika"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a5-7dae-b0c3-91a860a253f3"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Mass",
                            Name = "só",
                            NormalizedName = "só",
                            SeedKey = "so"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a6-79c2-a6b4-083b402ee44a"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Mass",
                            Name = "bors",
                            NormalizedName = "bors",
                            SeedKey = "bors"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a7-746d-8f8a-d6173bc02904"),
                            DefaultCategory = "Beverages",
                            Dimension = "Volume",
                            Name = "víz",
                            NormalizedName = "víz",
                            SeedKey = "viz"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a8-73cb-80de-f72ebcb3ba01"),
                            DefaultCategory = "Bakery",
                            Dimension = "Count",
                            Name = "kenyér",
                            NormalizedName = "kenyér",
                            SeedKey = "kenyer"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4a9-7c8f-a377-a19949681cea"),
                            DefaultCategory = "Bakery",
                            Dimension = "Count",
                            Name = "kifli",
                            NormalizedName = "kifli",
                            SeedKey = "kifli"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4aa-7019-8624-c1716ad4de7b"),
                            DefaultCategory = "Dairy",
                            Dimension = "Mass",
                            Name = "joghurt",
                            NormalizedName = "joghurt",
                            SeedKey = "joghurt"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4ab-7527-940b-7acd5b67aa7c"),
                            DefaultCategory = "Dairy",
                            Dimension = "Volume",
                            Name = "tejszín",
                            NormalizedName = "tejszín",
                            SeedKey = "tejszin"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4ac-74eb-8f00-38d37814a809"),
                            DefaultCategory = "Cheese",
                            Dimension = "Mass",
                            Name = "trappista sajt",
                            NormalizedName = "trappista sajt",
                            SeedKey = "trappista-sajt"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4ad-73e7-857a-7396a56d6d75"),
                            DefaultCategory = "FreshMeatFish",
                            Dimension = "Mass",
                            Name = "csirkemell",
                            NormalizedName = "csirkemell",
                            SeedKey = "csirkemell"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4ae-7bad-a26d-3db0c8e0bd77"),
                            DefaultCategory = "FreshMeatFish",
                            Dimension = "Mass",
                            Name = "darált sertéshús",
                            NormalizedName = "darált sertéshús",
                            SeedKey = "daralt-serteshus"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4af-7d94-a469-1140c47e4814"),
                            DefaultCategory = "ProcessedMeat",
                            Dimension = "Mass",
                            Name = "sonka",
                            NormalizedName = "sonka",
                            SeedKey = "sonka"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b0-7909-8e1b-b4a28be99399"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Mass",
                            Name = "rizs",
                            NormalizedName = "rizs",
                            SeedKey = "rizs"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b1-7548-9a34-96e76ef4d804"),
                            DefaultCategory = "DryGoods",
                            Dimension = "Mass",
                            Name = "cukor",
                            NormalizedName = "cukor",
                            SeedKey = "cukor"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b2-74ab-b11f-864af17fbd0d"),
                            DefaultCategory = "Fruit",
                            Dimension = "Count",
                            Name = "alma",
                            NormalizedName = "alma",
                            SeedKey = "alma"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b3-73fd-9f62-f5cab9dafa04"),
                            DefaultCategory = "Fruit",
                            Dimension = "Count",
                            Name = "banán",
                            NormalizedName = "banán",
                            SeedKey = "banan"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b4-7686-bb4b-9d3298a72b52"),
                            DefaultCategory = "Fruit",
                            Dimension = "Count",
                            Name = "citrom",
                            NormalizedName = "citrom",
                            SeedKey = "citrom"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b5-7e6f-80b9-dbcb7048edaa"),
                            DefaultCategory = "Vegetables",
                            Dimension = "Mass",
                            Name = "sárgarépa",
                            NormalizedName = "sárgarépa",
                            SeedKey = "sargarepa"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b6-72dc-9d01-ddf60e84df77"),
                            DefaultCategory = "Vegetables",
                            Dimension = "Count",
                            Name = "fokhagyma",
                            NormalizedName = "fokhagyma",
                            SeedKey = "fokhagyma"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b7-7546-a5a1-9b55e78e6dc0"),
                            DefaultCategory = "CannedAndSauces",
                            Dimension = "Mass",
                            Name = "paradicsompüré",
                            NormalizedName = "paradicsompüré",
                            SeedKey = "paradicsompure"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b8-70a8-92e7-887762859205"),
                            DefaultCategory = "Frozen",
                            Dimension = "Mass",
                            Name = "fagyasztott zöldborsó",
                            NormalizedName = "fagyasztott zöldborsó",
                            SeedKey = "fagyasztott-zoldborso"
                        },
                        new
                        {
                            Id = new Guid("01a126a0-f4b9-7b93-b485-297af03564e8"),
                            DefaultCategory = "Beverages",
                            Dimension = "Volume",
                            Name = "narancslé",
                            NormalizedName = "narancslé",
                            SeedKey = "narancsle"
                        });
                });

            modelBuilder.Entity("KamraApp.Domain.Pantry.PantryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnteredUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("ExpiryEstimated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("HouseholdId", "IngredientId", "ExpiryDate");

                    b.ToTable("PantryItems", t =>
                        {
                            t.HasCheckConstraint("CK_PantryItems_Quantity_NonNegative", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("KamraApp.Domain.Pantry.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Delta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateOnly>("ExpiryDateAtMovement")
                        .HasColumnType("date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PantryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("PantryItemId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("KamraApp.Infrastructure.Persistence.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KamraApp.Domain.Households.Household", b =>
                {
                    b.HasOne("KamraApp.Infrastructure.Persistence.AppUser", null)
                        .WithOne()
                        .HasForeignKey("KamraApp.Domain.Households.Household", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KamraApp.Domain.Ingredients.Ingredient", b =>
                {
                    b.HasOne("KamraApp.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KamraApp.Domain.Pantry.PantryItem", b =>
                {
                    b.HasOne("KamraApp.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KamraApp.Domain.Ingredients.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("KamraApp.Domain.Pantry.StockMovement", b =>
                {
                    b.HasOne("KamraApp.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KamraApp.Domain.Pantry.PantryItem", null)
                        .WithMany()
                        .HasForeignKey("PantryItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KamraApp.Infrastructure.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KamraApp.Infrastructure.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KamraApp.Infrastructure.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
